name: Test

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['10', '12', '14']
        name: Node ${{ matrix.node }} test

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node }}
            - run: npm ci
            - run: npm test
            - run: npm run lint:check
